[project]
name = "homework-02-typing"
version = "0.1.0"
description = "Just exercise for py Python education courses"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mypy>=1.9.0",
]
